import type { Lang } from "./i18n";
const languages = ["en", "ko", "ja", "zh", "hi", "es", "fr", "ar", "pt", "ru", "tr", "de", "vi"] as const;
const rows: Readonly<Record<string, readonly string[]>> = {
 partial: ["Some local records could not be read or were outside the scan limits. Totals may be incomplete.", "일부 로컬 기록을 읽지 못했거나 스캔 한도를 초과했습니다. 합계가 불완전할 수 있습니다.", "一部の記録を読めないか走査上限を超えました。合計は不完全な場合があります。", "部分记录无法读取或超出扫描限制，总量可能不完整。", "कुछ रिकॉर्ड पढ़े नहीं गए या सीमा से बाहर थे। कुल अपूर्ण हो सकता है।", "Algunos registros no se leyeron o superaron el límite. Los totales pueden ser incompletos.", "Certains relevés sont illisibles ou hors limites. Les totaux peuvent être incomplets.", "تعذر قراءة بعض السجلات أو تجاوزت حدود الفحص. قد يكون الإجمالي غير مكتمل.", "Alguns registros não foram lidos ou excederam limites. Totais podem estar incompletos.", "Часть записей недоступна или вне лимита сканирования. Суммы могут быть неполными.", "Bazı kayıtlar okunamadı veya tarama sınırını aştı. Toplamlar eksik olabilir.", "Einige Daten konnten nicht gelesen werden oder überschreiten Scanlimits. Summen können unvollständig sein.", "Một số dữ liệu không đọc được hoặc vượt giới hạn quét. Tổng có thể chưa đầy đủ."],
 history: ["Local history may include previously used accounts. Totals cannot be attributed to the current login.", "로컬 기록에는 이전에 사용한 계정이 포함될 수 있습니다. 토큰 합계를 현재 로그인 계정의 사용량으로 단정할 수 없습니다.", "以前のアカウントの記録も含む場合があります。現在のログインの使用量とは限りません。", "本地历史可能包含旧账号，总量不能归属于当前账号。", "पुराने खाते शामिल हो सकते हैं। कुल टोकन वर्तमान खाते से संबद्ध नहीं हैं।", "El historial puede incluir cuentas anteriores. Los totales no se atribuyen a la sesión actual.", "Les données peuvent inclure des comptes précédents. Les totaux ne sont pas attribuables au compte actuel.", "قد تتضمن البيانات حسابات سابقة. لا يمكن نسبة الإجمالي للحساب الحالي.", "O histórico pode incluir contas anteriores. Os totais não pertencem à conta atual.", "История может включать прежние аккаунты. Суммы не относятся к текущему входу.", "Geçmiş eski hesapları içerebilir. Toplamlar mevcut hesaba atanamaz.", "Daten können frühere Konten enthalten. Summen sind dem aktuellen Konto nicht zuzuordnen.", "Có thể gồm tài khoản cũ. Tổng token không thể quy cho tài khoản hiện tại."],
 stale: ["Expired or stale snapshot", "만료되었거나 오래된 기록", "期限切れまたは古い記録", "已过期或陈旧的快照", "पुराना या समाप्त रिकॉर्ड", "Registro caducado", "Relevé expiré ou ancien", "سجل قديم أو منتهي", "Registro expirado", "Устаревшая запись", "Eski veya süresi dolmuş kayıt", "Veraltete Aufzeichnung", "Bản ghi cũ hoặc hết hạn"],
 claude_quota_unavailable: ["Claude live quota unavailable.", "Claude 실시간 한도를 가져올 수 없습니다.", "Claude利用枠を取得できません。", "无法获取Claude实时配额。", "Claude कोटा उपलब्ध नहीं।", "Cuota Claude no disponible.", "Quota Claude indisponible.", "حصة Claude غير متاحة.", "Cota Claude indisponível.", "Квота Claude недоступна.", "Claude kotası alınamadı.", "Claude-Kontingent nicht verfügbar.", "Không lấy được hạn ngạch Claude."],
 claude_quota_stale: ["Claude quota refresh failed; showing a recorded snapshot.", "Claude 한도 갱신 실패: 이전 기록을 표시합니다.", "Claude利用枠の更新失敗。過去の記録を表示。", "Claude配额更新失败，显示历史快照。", "Claude कोटा अपडेट विफल; पुराना रिकॉर्ड।", "Error al actualizar cuota Claude; registro anterior.", "Actualisation Claude échouée ; ancien relevé.", "فشل تحديث حصة Claude؛ عرض سجل سابق.", "Falha ao atualizar cota Claude; registro anterior.", "Обновление квоты Claude не удалось; показана запись.", "Claude kotası yenilenemedi; eski kayıt gösteriliyor.", "Claude-Kontingentaktualisierung fehlgeschlagen; gespeicherter Stand.", "Làm mới hạn ngạch Claude thất bại; hiển thị bản ghi cũ."],
 title: ["AI token usage", "AI 토큰 사용량", "AIトークン使用量", "AI令牌使用量", "AI टोकन उपयोग", "Uso de tokens de IA", "Utilisation des jetons IA", "استخدام رموز الذكاء الاصطناعي", "Uso de tokens de IA", "Использование токенов ИИ", "AI token kullanımı", "KI-Tokenverbrauch", "Sử dụng token AI"],
 five_hour: ["Last 5 hours", "최근 5시간", "過去5時間", "最近5小时", "पिछले 5 घंटे", "Últimas 5 horas", "5 dernières heures", "آخر 5 ساعات", "Últimas 5 horas", "Последние 5 часов", "Son 5 saat", "Letzte 5 Stunden", "5 giờ qua"],
 seven_day: ["Last 7 days", "최근 7일", "過去7日", "最近7天", "पिछले 7 दिन", "Últimos 7 días", "7 derniers jours", "آخر 7 أيام", "Últimos 7 dias", "Последние 7 дней", "Son 7 gün", "Letzte 7 Tage", "7 ngày qua"],
 all_time: ["All recorded usage", "전체 기록 사용량", "全記録の使用量", "全部记录", "सभी रिकॉर्ड", "Todo el uso registrado", "Tout l’usage enregistré", "كل الاستخدام المسجل", "Todo o uso registrado", "Все записи", "Tüm kayıtlar", "Alle Aufzeichnungen", "Toàn bộ dữ liệu"],
 provider: ["AI provider", "AI 제공자", "AIプロバイダー", "AI提供商", "AI प्रदाता", "Proveedor IA", "Fournisseur IA", "مزود الذكاء الاصطناعي", "Provedor IA", "Провайдер ИИ", "AI sağlayıcı", "KI-Anbieter", "Nhà cung cấp AI"],
 model: ["Model", "모델", "モデル", "模型", "मॉडल", "Modelo", "Modèle", "النموذج", "Modelo", "Модель", "Model", "Modell", "Mô hình"],
 project: ["Project", "프로젝트", "プロジェクト", "项目", "प्रोजेक्ट", "Proyecto", "Projet", "المشروع", "Projeto", "Проект", "Proje", "Projekt", "Dự án"],
 input: ["Input", "입력", "入力", "输入", "इनपुट", "Entrada", "Entrée", "الإدخال", "Entrada", "Вход", "Girdi", "Eingabe", "Đầu vào"],
 output: ["Output", "출력", "出力", "输出", "आउटपुट", "Salida", "Sortie", "الإخراج", "Saída", "Выход", "Çıktı", "Ausgabe", "Đầu ra"],
 cache_read: ["Cache read", "캐시 읽기", "キャッシュ読取", "缓存读取", "कैश पढ़ना", "Lectura de caché", "Lecture du cache", "قراءة التخزين المؤقت", "Leitura de cache", "Чтение кэша", "Önbellek okuma", "Cache lesen", "Đọc bộ nhớ đệm"],
 cache_write: ["Cache write", "캐시 쓰기", "キャッシュ書込", "缓存写入", "कैश लिखना", "Escritura de caché", "Écriture du cache", "كتابة التخزين المؤقت", "Gravação de cache", "Запись кэша", "Önbellek yazma", "Cache schreiben", "Ghi bộ nhớ đệm"],
 total: ["Total tokens", "총 토큰", "合計トークン", "总令牌", "कुल टोकन", "Tokens totales", "Total des jetons", "إجمالي الرموز", "Total de tokens", "Всего токенов", "Toplam token", "Token gesamt", "Tổng token"],
 refresh: ["Refresh", "새로고침", "更新", "刷新", "ताज़ा करें", "Actualizar", "Actualiser", "تحديث", "Atualizar", "Обновить", "Yenile", "Aktualisieren", "Làm mới"],
 close: ["Close", "닫기", "閉じる", "关闭", "बंद करें", "Cerrar", "Fermer", "إغلاق", "Fechar", "Закрыть", "Kapat", "Schließen", "Đóng"],
 loading: ["Reading local usage…", "로컬 사용 기록 읽는 중…", "ローカル記録を読込中…", "正在读取本地记录…", "स्थानीय रिकॉर्ड पढ़ रहे हैं…", "Leyendo registros locales…", "Lecture des données locales…", "قراءة السجلات المحلية…", "Lendo registros locais…", "Чтение локальных записей…", "Yerel kayıtlar okunuyor…", "Lokale Daten werden gelesen…", "Đang đọc dữ liệu cục bộ…"],
 empty: ["No token records in this window.", "이 기간에 토큰 기록이 없습니다.", "この期間の記録はありません。", "此时间段无记录。", "इस अवधि में रिकॉर्ड नहीं।", "No hay registros en este período.", "Aucun relevé pour cette période.", "لا توجد سجلات لهذه الفترة.", "Sem registros neste período.", "Нет записей за этот период.", "Bu dönemde kayıt yok.", "Keine Daten für diesen Zeitraum.", "Không có dữ liệu trong khoảng này."],
 unknown: ["Unknown", "알 수 없음", "不明", "未知", "अज्ञात", "Desconocido", "Inconnu", "غير معروف", "Desconhecido", "Неизвестно", "Bilinmiyor", "Unbekannt", "Không rõ"],
 credentials_present: ["Local credentials found", "로컬 인증 정보 감지", "ローカル認証情報あり", "发现本地凭据", "स्थानीय क्रेडेंशियल मिले", "Credenciales locales detectadas", "Identifiants locaux détectés", "تم العثور على بيانات اعتماد محلية", "Credenciais locais detectadas", "Найдены локальные учетные данные", "Yerel kimlik bilgileri bulundu", "Lokale Anmeldedaten gefunden", "Tìm thấy thông tin đăng nhập cục bộ"],
 not_detected: ["Credentials not detected", "인증 정보 미감지", "認証情報未検出", "未检测到凭据", "क्रेडेंशियल नहीं मिले", "Credenciales no detectadas", "Identifiants non détectés", "لم يتم اكتشاف بيانات اعتماد", "Credenciais não detectadas", "Учетные данные не найдены", "Kimlik bilgileri bulunamadı", "Keine Anmeldedaten erkannt", "Không tìm thấy thông tin đăng nhập"],
 quota: ["Recorded quota usage", "기록된 한도 사용률", "記録された利用率", "记录的配额用量", "रिकॉर्ड किया गया कोटा उपयोग", "Cuota registrada", "Quota enregistré", "استخدام الحصة المسجل", "Cota registrada", "Записанное использование квоты", "Kaydedilen kota kullanımı", "Aufgezeichnete Kontingentnutzung", "Mức hạn ngạch đã ghi"],
 observed: ["Recorded at", "기록 시각", "記録日時", "记录时间", "रिकॉर्ड समय", "Registrado", "Enregistré", "وقت التسجيل", "Registrado", "Время записи", "Kayıt zamanı", "Aufgezeichnet am", "Ghi lúc"],
 resets: ["Resets at", "초기화 시각", "リセット日時", "重置时间", "रीसेट समय", "Se reinicia", "Réinitialisation", "وقت إعادة التعيين", "Redefinição", "Время сброса", "Sıfırlama zamanı", "Zurücksetzung", "Đặt lại lúc"],
 limitations: ["Local Claude Code / Codex CLI token totals exclude other devices and web chats. Rolling totals are not subscription limits. Credentials do not confirm an active login. Claude quota snapshots cover the whole account and may be stale.", "로컬 Claude Code / Codex CLI 토큰 합계에는 다른 기기와 웹 채팅이 포함되지 않습니다. 최근 기간 합계는 구독 한도가 아닙니다. 인증 정보는 현재 로그인 유효성을 보장하지 않습니다. Claude 한도 기록은 계정 전체 기준이며 오래된 값일 수 있습니다.", "ローカルClaude Code / Codex CLI合計は他の端末やウェブチャットを含みません。合計は契約上限ではありません。認証情報は有効なログインを保証しません。Claude利用枠はアカウント全体の記録で古い場合があります。", "本地Claude Code / Codex CLI令牌总量不含其他设备和网页聊天，非订阅限额。凭据不保证有效登录。Claude配额快照覆盖整个账号，可能过时。", "स्थानीय Claude Code / Codex CLI टोकन योग में अन्य डिवाइस और वेब चैट नहीं हैं। योग सदस्यता सीमा नहीं हैं। क्रेडेंशियल सक्रिय लॉगिन की पुष्टि नहीं करते। Claude कोटा पूरे खाते का है और पुराना हो सकता है।", "Totales locales Claude Code / Codex CLI sin otros dispositivos ni chats web; no son límites de suscripción. Las credenciales no confirman la sesión. La cuota Claude cubre toda la cuenta y puede estar desactualizada.", "Totaux locaux Claude Code / Codex CLI hors autres appareils et chats web ; ce ne sont pas les limites d’abonnement. Les identifiants ne confirment pas la connexion. Le quota Claude couvre tout le compte et peut être ancien.", "إجمالي رموز Claude Code / Codex CLI المحلية لا يشمل الأجهزة الأخرى ودردشة الويب وليس حد الاشتراك. بيانات الاعتماد لا تؤكد الدخول. حصة Claude تشمل الحساب بالكامل وقد تكون قديمة.", "Totais locais Claude Code / Codex CLI excluem outros dispositivos e chats web; não são limites da assinatura. Credenciais não confirmam login. A cota Claude abrange toda a conta e pode estar desatualizada.", "Локальные суммы Claude Code / Codex CLI не включают другие устройства и веб-чаты и не являются лимитами подписки. Учетные данные не подтверждают вход. Квота Claude относится ко всему аккаунту и может устареть.", "Yerel Claude Code / Codex CLI toplamları diğer cihazları ve web sohbetlerini içermez; abonelik sınırı değildir. Kimlik bilgileri aktif oturumu doğrulamaz. Claude kotası tüm hesabı kapsar ve eski olabilir.", "Lokale Claude Code / Codex CLI-Summen schließen andere Geräte und Webchats aus und sind keine Abonnementlimits. Anmeldedaten bestätigen keine Sitzung. Claude-Kontingente gelten für das gesamte Konto und können veraltet sein.", "Tổng token Claude Code / Codex CLI cục bộ không gồm thiết bị khác và chat web, không phải giới hạn đăng ký. Thông tin đăng nhập không xác nhận phiên hoạt động. Hạn ngạch Claude gồm cả tài khoản và có thể cũ."],
 error: ["Could not read token usage. Try refreshing.", "토큰 기록을 읽지 못했습니다. 새로고침해 주세요.", "記録を読めません。更新してください。", "无法读取记录，请刷新。", "रिकॉर्ड नहीं पढ़ सके। फिर से प्रयास करें।", "No se pudo leer el uso. Actualice.", "Lecture impossible. Actualisez.", "تعذر قراءة الاستخدام. أعد التحديث.", "Falha ao ler uso. Atualize.", "Не удалось прочитать данные. Обновите.", "Kullanım okunamadı. Yenileyin.", "Daten konnten nicht gelesen werden. Aktualisieren Sie.", "Không đọc được dữ liệu. Hãy làm mới."],
};
export const tokenStrings: Record<string, Partial<Record<Lang, string>>> = {};
for (const [key, values] of Object.entries(rows)) {
  const entry: Partial<Record<Lang, string>> = {};
  languages.forEach((lang, index) => { entry[lang] = values[index]; });
  tokenStrings[`usage.${key}`] = entry;
}
for (const code of ["collector_unavailable", "claude_file_limit", "codex_file_limit", "claude_partial", "codex_partial", "claude_scan_limit", "codex_scan_limit"] as const) {
  tokenStrings[`usage.${code}`] = tokenStrings["usage.partial"];
}
